#pragma config(Sensor, in1,    analog1,        sensorAnalog)
#pragma config(Sensor, dgtl1,  beaconswitch,   sensorTouch)
#pragma config(Sensor, dgtl2,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl10, digital10,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, digital11,      sensorDigitalOut)
#pragma config(Sensor, dgtl12, digital12,      sensorDigitalOut)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Global Variables
int freq, ambient_level, slow_level, stop_level, expose_time, steer_sensitivity, forward_speed, slow_speed, spin_speed;

// initialize PD values for the global uses - will be modified at the appropriate timing in ReadPD function.
int PD0, PD1, PD2, PD3, PD4, PD5, PD6, PD7, PD_sum;
// initialize max values
int max_val, max_no = 0;

enum Phases {
		PHASE_GOTO_RED,
		PHASE_ACTIVATE_RED,
		PHASE_REVERSE_RED,
		PHASE_GOTO_GREEN,
		PHASE_PREEMPTIVE_ROTATION,
		PHASE_RETURN_HOME
};
enum Phases phase = PHASE_GOTO_RED;

/*The accumulator accumulates(or integrates) the rectified signal over a period of time (set by the  )
The accumulated voltage read by SensorValue[analog1](an analog voltage) is read by the controller.
The expose_time period essentially set the ?gain? or ?sensitivity? of the overall circuit.*/
int Expose_and_read(){
	SensorValue[digital11] = 1; // close the shutter, clear the film, and increment the counter
	delay(5); // Wait for 5ms for things to settle
	SensorValue[digital11] = 0; // open shutter for exposure
	delay(expose_time); // expose time = 3ms to 8ms (can be adjusted)
	int intensity = SensorValue[analog1]; // get the IR intensity reading
	return intensity; // return the analog input 1
}

/*Read_PD calculates PD_sum which is the sum of all 8 photo diodes?outputs.
PD_sum is a measure of the distance between the robot and the beacon. The sensing
sensitivity is set by expose_time*/

void ReadPD(){
	SensorValue[digital11] = 1; // close the shutter, clear the film, and increment the counter
	SensorValue[digital12] = 1; // initialize counter value to '0'
	SensorValue[digital12] = 0; // allow counter to count
	delay(5); // 5ms wait for things settling down
	SensorValue[digital11] = 0; // open shutter and expose film
	delay(expose_time); // expose time = 3ms to 8ms (can be adjusted)
	PD0 = SensorValue[analog1];
	PD1 = Expose_and_read();
	PD2 = Expose_and_read();
	PD3 = Expose_and_read();
	PD4 = Expose_and_read();
	PD5 = Expose_and_read();
	PD6 = Expose_and_read();
	PD7 = Expose_and_read();
	PD_sum = PD0 + PD1 + PD2 + PD3 + PD4 + PD5 + PD6 + PD7;
}

/*This function compares the magnitude of the variables PD0~PD7 and stores the maximum value
in max_val and the number of the photo diode that has the maximum value in max_no.*/

void Find_max(){
	max_val = PD0; // default = PD0;
	max_no = 0;

	if(PD1 > max_val){
		max_val = PD1;
		max_no = 1;
	}
	if(PD2 > max_val){
		max_val = PD2;
		max_no = 2;
	}
	if(PD3 > max_val){
		max_val = PD3;
		max_no = 3;
	}
	if(PD4 > max_val){
		max_val = PD4;
		max_no = 4;
	}
	if(PD5 > max_val){
		max_val = PD5;
		max_no = 5;
	}
	if(PD6 > max_val){
		max_val = PD6;
		max_no = 6;
	}
	if(PD7 > max_val){
		max_val = PD7;
		max_no = 7;
	}
}

/*
Limits results of move function to max speed	and output to the motors*/
int limit_pwm(int temp){
	int limited = 0;

	if(temp > 127){
		limited = 127;
	} else if (temp < -127){
		limited = -127;
	} else{
		limited = temp;
	}

	return limited;

}

/*Move function helps to check if beacon is found or otherwise it will be search mode	 looking for the beacon.
This function also calculates the speed, steering sensitivity and the heading direction so the robot moves to beacon*/

void Move(){
	int tempSpeed = 0;
	int error = 4 - max_no;//heading direction error , if PD4==max_no, then no error
	int steer = -error * steer_sensitivity;//steering effort is proportioinal to heading error
	int speed = forward_speed;//forward speed (normal speed)

	if(PD_sum < ambient_level){ // looking for the beacon if background noise is
		speed = 0;//serach mode=>no forward motion
		steer = -spin_speed;//search mode =>spin
	}
	if(PD_sum > slow_level){//Beacon is near!
		speed = slow_speed;//slow down
	}
	// deleted the stop statement when the beacon is found, because we'll	 use the limit switch to stop the motors	which is more reliable.


	tempSpeed = limit_pwm(steer + speed);
	datalogAddValue(4, tempSpeed);
	motor[rightMotor] = tempSpeed; // right, port 1
	tempSpeed = limit_pwm(steer - speed);
	datalogAddValue(5, tempSpeed);
	motor[leftMotor] = tempSpeed; // left, port	 10
}

/*
The GOBEACON main program essentially sets up all the configuration variables and repeatedly
execute the three routines: Read_PD, find_max, and move.*/
task main(){
	freq = 0; // 0 = 1khz (red) 1 = 10khz (green)
	ambient_level = 500; // used in 'move'
	slow_level = 5000;// used in move
	stop_level = 6000;//used in move
	expose_time = 5; // expose time was changed from 3ms to 5ms (3ms in easyC -> 5ms in RobotC)
	steer_sensitivity = 20;//used in move
	forward_speed = 70;//forward speed , used in move
	slow_speed = 25;//slow speed , used in move
	spin_speed = 50;//spin speed (for searching mode),used in move
	SensorValue[digital10] = freq;// turn to 1KHz(red beacon)


	phase = PHASE_GOTO_RED;

	long rotation_sum = 0;
	clearTimer(T2);
	while(true){
		switch (phase) {
			case PHASE_GOTO_RED:
				ReadPD();
				Find_max();

				rotation_sum += (motor[rightMotor] + motor[leftMotor]) * time1[T2];
			  clearTimer(T2);

				Move();
				if (SensorValue[beaconswitch]) phase = PHASE_ACTIVATE_RED;
				break;
			case PHASE_ACTIVATE_RED:
				rotation_sum += (motor[rightMotor] + motor[leftMotor]) * time1[T2];
				clearTimer(T2);
				motor[leftMotor] = -127;
				motor[rightMotor] = 127;
				ReadPD();
				if (PD_sum < 2000) phase = PHASE_REVERSE_RED;
				break;
			case PHASE_REVERSE_RED:
				rotation_sum += (motor[rightMotor] + motor[leftMotor]) * time1[T2];
				clearTimer(T2);
				motor[leftMotor] = 127;
				motor[rightMotor] = -127;
				delay(750); // TODO: make better of necessary
				phase = PHASE_GOTO_GREEN;
				break;
			case PHASE_GOTO_GREEN:
				freq = 1; // switch read frequency to green
				SensorValue[digital10] = freq;
				ReadPD();
				Find_max();
				rotation_sum += (motor[rightMotor] + motor[leftMotor]) * time1[T2];
				clearTimer(T2);
				Move();
				if (SensorValue[beaconswitch]) phase = PHASE_PREEMPTIVE_ROTATION;
				break;
			case PHASE_PREEMPTIVE_ROTATION:
				int rotationSign = sgn(rotation_sum);
				if (rotationSign < 0) // leftMotor dominated first half
					motor[rightMotor] = 127;
			  else motor[leftMotor] = 127;
				delay(rotation_sum/127);
				phase = PHASE_RETURN_HOME;
				break;
			case PHASE_RETURN_HOME:
				motor[leftMotor] = -forward_speed;
				motor[rightMotor] = forward_speed;
				if (SensorValue[sonar] < 15) {
					motor[leftMotor] = -1;
					motor[rightMotor] = forward_speed;
				}
				delay(1);

		}
		datalogAddValue(0, PD_sum);
		datalogAddValue(1, motor[leftMotor]);
		datalogAddValue(2, motor[rightMotor]);
		datalogAddValue(3,phase);
	}

	end_all:
	// Nothing
}
