#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int x = 0;
	while(++x){
		datalogAddValue(1,SensorValue[sonar]);
		delay(100);
	}
}
// d = 3in
// h = 3 7/8
